language: cpp
compiler:
  - g++
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nasm g++-4.6-multilib gcc-multilib libc6-dev-i386
install:
  - make gmp-bootstrap
  - make gtest-bootstrap
script:
  - make -B ENABLE64BIT=Yes
  - make ENABLE64BIT=Yes plugin
  - make ENABLE64BIT=Yes test
  - make -B ENABLE64BIT=Yes BUILDTYPE=Debug
  - make ENABLE64BIT=Yes BUILDTYPE=Debug plugin
  - make ENABLE64BIT=Yes test
  - make -B ENABLE64BIT=No
  - make ENABLE64BIT=No plugin
  - make ENABLE64BIT=No test
  - make -B ENABLE64BIT=No BUILDTYPE=Debug
  - make ENABLE64BIT=No BUILDTYPE=Debug plugin
  - make ENABLE64BIT=No test
