language: cpp

compiler:
  - g++
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nasm g++-4.6-multilib gcc-multilib libc6-dev-i386

install:
  - make gmp-bootstrap
  - make gtest-bootstrap

before_script:
  - WorkingDir=`pwd`
  - cd test/encoder_binary_comparison
  - ./run_PrepareAllTestData.sh 64
  - cd ${WorkingDir}

env:
  - TASK=UnitTest;      TestParameter=""
  - TASK=BinaryCompare; TestParameter=BA_MW_D.264
  - TASK=BinaryCompare; TestParameter=CVPCMNL1_SVA_C.264

matrix:
  exclude:
    - compiler: clang
      env: TASK=BinaryCompare; TestParameter=BA_MW_D.264
    - compiler: clang
      env: TASK=BinaryCompare; TestParameter=CVPCMNL1_SVA_C.264
script:
  -  echo "currrent test is for ${TASK}"
  -  echo "test parameter is ${TestParameter}"
  -  ./run_Test.sh ${TASK}  ${TestParameter}
